[Variables]
WHome=["D:\Wallpaper-Engine-SteamRIP.com\Wallpaper Engine\wallpaper64.exe" -control openWallpaper -file "D:\Wallpaper-Engine-SteamRIP.com\Wallpaper Engine\projects\myprojects\Mavis_Zeref\project.json"]
WGrid=["D:\Wallpaper-Engine-SteamRIP.com\Wallpaper Engine\wallpaper64.exe" -control openWallpaper -file "D:\Wallpaper-Engine-SteamRIP.com\Wallpaper Engine\projects\myprojects\hammel-frieren\project.json"]
WShop=
WDungeon=["D:\Wallpaper-Engine-SteamRIP.com\Wallpaper Engine\wallpaper64.exe" -control openWallpaper -file "D:\Wallpaper-Engine-SteamRIP.com\Wallpaper Engine\projects\myprojects\rezero\project.json"]
WRaid=["D:\Wallpaper-Engine-SteamRIP.com\Wallpaper Engine\wallpaper64.exe" -control openWallpaper -file "D:\Wallpaper-Engine-SteamRIP.com\Wallpaper Engine\projects\myprojects\Kirito_Asuna\project.json"]
WQuest=
