[Variables]
PixelSize=17.5
GapSize=0.25
ArrayWidth=18
ArrayHeight=14
AlbumFontSize=24
FontContrast=0,0,0,255
Classic=StrokeLineJoin Miter
Linear=StrokeDashCap Flat | StrokeDashOffset 0  | StrokeDashes 1,#GapSize#
Square=StrokeDashCap Square | StrokeDashOffset 0.75 | StrokeDashes 0,(1+#GapSize#)
Circle=StrokeDashCap Round | StrokeDashOffset 0.75 | StrokeDashes 0,(1+#GapSize#)
Diamond=StrokeDashCap Triangle | StrokeDashOffset 0.75 | StrokeDashes 0,(1+#GapSize#)
PixelType=#Classic#
GradientPoint=0.75
GradientAngle=22.5
